/*
 * Domain API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainDataDigitalCertificateId {
}

impl DomainDataDigitalCertificateId {
    pub fn new() -> DomainDataDigitalCertificateId {
        DomainDataDigitalCertificateId {
        }
    }
}

