/*
 * Domain API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutDomainRequest {
    #[serde(rename = "cnames")]
    pub cnames: Vec<String>,
    #[serde(rename = "cname_access_only")]
    pub cname_access_only: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "edge_application_id")]
    pub edge_application_id: i64,
    #[serde(rename = "digital_certificate_id", deserialize_with = "Option::deserialize")]
    pub digital_certificate_id: Option<i64>,
}

impl PutDomainRequest {
    pub fn new(cnames: Vec<String>, cname_access_only: bool, name: String, is_active: bool, edge_application_id: i64, digital_certificate_id: Option<i64>) -> PutDomainRequest {
        PutDomainRequest {
            cnames,
            cname_access_only,
            name,
            is_active,
            edge_application_id,
            digital_certificate_id,
        }
    }
}


