/*
 * Data Streaming - OpenAPI
 *
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataStreamingEndpointTypeStandardHeadersExample {
    #[serde(rename = "header-name-1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub header_name_1: Option<Option<String>>,
    #[serde(rename = "header-name-2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub header_name_2: Option<Option<String>>,
    #[serde(rename = "header-name-3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub header_name_3: Option<Option<String>>,
}

impl DataStreamingEndpointTypeStandardHeadersExample {
    pub fn new() -> DataStreamingEndpointTypeStandardHeadersExample {
        DataStreamingEndpointTypeStandardHeadersExample {
            header_name_1: None,
            header_name_2: None,
            header_name_3: None,
        }
    }
}


