/*
 * Data Streaming - OpenAPI
 *
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EndpointGoogleBigQuery {
    #[serde(rename = "endpoint_type", skip_serializing_if = "Option::is_none")]
    pub endpoint_type: Option<String>,
    #[serde(rename = "dataset_id", skip_serializing_if = "Option::is_none")]
    pub dataset_id: Option<String>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "table_id", skip_serializing_if = "Option::is_none")]
    pub table_id: Option<String>,
    #[serde(rename = "service_account_key", skip_serializing_if = "Option::is_none")]
    pub service_account_key: Option<Box<crate::models::EndpointGoogleBigQueryServiceAccountKey>>,
}

impl EndpointGoogleBigQuery {
    pub fn new() -> EndpointGoogleBigQuery {
        EndpointGoogleBigQuery {
            endpoint_type: None,
            dataset_id: None,
            project_id: None,
            table_id: None,
            service_account_key: None,
        }
    }
}


