/*
 * Edge Functions Instances API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEdgeFunctionsInstancesRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "edge_function", skip_serializing_if = "Option::is_none")]
    pub edge_function: Option<i64>,
    #[serde(rename = "json_args", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub json_args: Option<Option<serde_json::Value>>,
}

impl CreateEdgeFunctionsInstancesRequest {
    pub fn new() -> CreateEdgeFunctionsInstancesRequest {
        CreateEdgeFunctionsInstancesRequest {
            name: None,
            edge_function: None,
            json_args: None,
        }
    }
}


