/*
 * Edge Functions Instances API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EdgeFunctionsInstance {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "json_args", skip_serializing_if = "Option::is_none")]
    pub json_args: Option<serde_json::Value>,
    #[serde(rename = "edge_function", skip_serializing_if = "Option::is_none")]
    pub edge_function: Option<i32>,
}

impl EdgeFunctionsInstance {
    pub fn new() -> EdgeFunctionsInstance {
        EdgeFunctionsInstance {
            id: None,
            name: None,
            json_args: None,
            edge_function: None,
        }
    }
}


