/*
 * Web Application Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WafDomainList200 {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "cnames", skip_serializing_if = "Option::is_none")]
    pub cnames: Option<Vec<String>>,
}

impl WafDomainList200 {
    pub fn new() -> WafDomainList200 {
        WafDomainList200 {
            id: None,
            name: None,
            domain: None,
            cnames: None,
        }
    }
}


