/*
 * Credentials API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthToken {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "last_editor")]
    pub last_editor: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl AuthToken {
    pub fn new(client_id: String, created_at: String, id: i64, is_active: bool, last_editor: String, name: String, token: String, updated_at: String) -> AuthToken {
        AuthToken {
            client_id,
            created_at,
            deleted_at: None,
            description: None,
            id,
            is_active,
            last_editor,
            name,
            token,
            updated_at,
        }
    }
}


