/*
 * Intelligent DNS
 *
 * Azion Intelligent DNS API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DnsSecDelegationSignerDigestType {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}

impl DnsSecDelegationSignerDigestType {
    pub fn new() -> DnsSecDelegationSignerDigestType {
        DnsSecDelegationSignerDigestType {
            id: None,
            slug: None,
        }
    }
}


