/*
 * Edge Function API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEdgeFunctionRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "json_args", skip_serializing_if = "Option::is_none")]
    pub json_args: Option<Box<models::CreateEdgeFunctionRequestJsonArgs>>,
    #[serde(rename = "initiator_type", skip_serializing_if = "Option::is_none")]
    pub initiator_type: Option<InitiatorType>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "is_proprietary_code", skip_serializing_if = "Option::is_none")]
    pub is_proprietary_code: Option<bool>,
}

impl CreateEdgeFunctionRequest {
    pub fn new() -> CreateEdgeFunctionRequest {
        CreateEdgeFunctionRequest {
            name: None,
            language: None,
            code: None,
            json_args: None,
            initiator_type: None,
            active: None,
            is_proprietary_code: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InitiatorType {
    #[serde(rename = "edge_application")]
    EdgeApplication,
    #[serde(rename = "edge_firewall")]
    EdgeFirewall,
}

impl Default for InitiatorType {
    fn default() -> InitiatorType {
        Self::EdgeApplication
    }
}

