/*
 * Edge Function
 *
 * Azion Edge Function API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorModel {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl ErrorModel {
    pub fn new() -> ErrorModel {
        ErrorModel {
            code: None,
        }
    }
}


