/*
 * Edge Function
 *
 * Azion Edge Function API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchEdgeFunctionRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "json_args", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub json_args: Option<Option<serde_json::Value>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl PatchEdgeFunctionRequest {
    pub fn new() -> PatchEdgeFunctionRequest {
        PatchEdgeFunctionRequest {
            name: None,
            code: None,
            json_args: None,
            active: None,
        }
    }
}


