/*
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BehaviorsArgument {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "limit_by", skip_serializing_if = "Option::is_none")]
    pub limit_by: Option<LimitBy>,
    #[serde(rename = "average_rate_limit", skip_serializing_if = "Option::is_none")]
    pub average_rate_limit: Option<i32>,
    #[serde(rename = "maximum_burst_size", skip_serializing_if = "Option::is_none")]
    pub maximum_burst_size: Option<i32>,
    #[serde(rename = "waf_id", skip_serializing_if = "Option::is_none")]
    pub waf_id: Option<i32>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
}

impl BehaviorsArgument {
    pub fn new() -> BehaviorsArgument {
        BehaviorsArgument {
            name: None,
            r#type: None,
            limit_by: None,
            average_rate_limit: None,
            maximum_burst_size: None,
            waf_id: None,
            mode: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "second")]
    Second,
    #[serde(rename = "minute")]
    Minute,
}

impl Default for Type {
    fn default() -> Type {
        Self::Second
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LimitBy {
    #[serde(rename = "client_ip")]
    ClientIp,
    #[serde(rename = "global")]
    Global,
}

impl Default for LimitBy {
    fn default() -> LimitBy {
        Self::ClientIp
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "Learning")]
    Learning,
    #[serde(rename = "Blocking")]
    Blocking,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Learning
    }
}

