/*
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetWafRuleSetAndWafModeBehaviorArgument {
    #[serde(rename = "set_waf_ruleset_and_waf_mode")]
    pub set_waf_ruleset_and_waf_mode: i32,
    #[serde(rename = "waf_mode")]
    pub waf_mode: WafMode,
}

impl SetWafRuleSetAndWafModeBehaviorArgument {
    pub fn new(set_waf_ruleset_and_waf_mode: i32, waf_mode: WafMode) -> SetWafRuleSetAndWafModeBehaviorArgument {
        SetWafRuleSetAndWafModeBehaviorArgument {
            set_waf_ruleset_and_waf_mode,
            waf_mode,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WafMode {
    #[serde(rename = "learning")]
    Learning,
    #[serde(rename = "blocking")]
    Blocking,
}

impl Default for WafMode {
    fn default() -> WafMode {
        Self::Learning
    }
}

