/*
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetWafRuleSetBehaviorArgument {
    #[serde(rename = "waf_id", skip_serializing_if = "Option::is_none")]
    pub waf_id: Option<i32>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
}

impl SetWafRuleSetBehaviorArgument {
    pub fn new() -> SetWafRuleSetBehaviorArgument {
        SetWafRuleSetBehaviorArgument {
            waf_id: None,
            mode: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "learning")]
    Learning,
    #[serde(rename = "blocking")]
    Blocking,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Learning
    }
}

