/*
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetCustomResponseArgument {
    #[serde(rename = "status_code")]
    pub status_code: Box<crate::models::SetCustomResponseArgumentStatusCode>,
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "content_body")]
    pub content_body: String,
}

impl SetCustomResponseArgument {
    pub fn new(status_code: crate::models::SetCustomResponseArgumentStatusCode, content_type: String, content_body: String) -> SetCustomResponseArgument {
        SetCustomResponseArgument {
            status_code: Box::new(status_code),
            content_type,
            content_body,
        }
    }
}


