/*
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SslVerificationStatusCriteria {
    #[serde(rename = "variable", skip_serializing_if = "Option::is_none")]
    pub variable: Option<crate::models::Variables>,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<crate::models::SslVerificationStatusOperators>,
    #[serde(rename = "conditional", skip_serializing_if = "Option::is_none")]
    pub conditional: Option<crate::models::Conditionals>,
    #[serde(rename = "input_value", skip_serializing_if = "Option::is_none")]
    pub input_value: Option<crate::models::SslVerificationStatusArguments>,
}

impl SslVerificationStatusCriteria {
    pub fn new() -> SslVerificationStatusCriteria {
        SslVerificationStatusCriteria {
            variable: None,
            operator: None,
            conditional: None,
            input_value: None,
        }
    }
}


