/*
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SslVerificationStatusArguments {
    #[serde(rename = "SUCCESS")]
    Success,
    #[serde(rename = "CERTIFICATE_VERIFICATION_ERROR")]
    CertificateVerificationError,
    #[serde(rename = "MISSING_CLIENT_CERTIFICATE")]
    MissingClientCertificate,

}

impl ToString for SslVerificationStatusArguments {
    fn to_string(&self) -> String {
        match self {
            Self::Success => String::from("SUCCESS"),
            Self::CertificateVerificationError => String::from("CERTIFICATE_VERIFICATION_ERROR"),
            Self::MissingClientCertificate => String::from("MISSING_CLIENT_CERTIFICATE"),
        }
    }
}

impl Default for SslVerificationStatusArguments {
    fn default() -> SslVerificationStatusArguments {
        Self::Success
    }
}




