/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthorizeEdgeNodesRequest {
    #[serde(rename = "edge_node_ids")]
    pub edge_node_ids: Vec<i64>,
}

impl AuthorizeEdgeNodesRequest {
    pub fn new(edge_node_ids: Vec<i64>) -> AuthorizeEdgeNodesRequest {
        AuthorizeEdgeNodesRequest {
            edge_node_ids,
        }
    }
}


