/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EdgeNodeResponse {
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<crate::models::NodeGroup>>,
    #[serde(rename = "hash_id", skip_serializing_if = "Option::is_none")]
    pub hash_id: Option<String>,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl EdgeNodeResponse {
    pub fn new(id: i64) -> EdgeNodeResponse {
        EdgeNodeResponse {
            groups: None,
            hash_id: None,
            id,
            name: None,
            status: None,
        }
    }
}


