/*
 * Edge Node API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EdgeNodeDetailResponse {
    #[serde(rename = "groups")]
    pub groups: Vec<crate::models::NodeGroup>,
    #[serde(rename = "has_services")]
    pub has_services: bool,
    #[serde(rename = "hash_id")]
    pub hash_id: String,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "modules")]
    pub modules: Box<crate::models::EdgeNodeModules>,
    #[serde(rename = "name")]
    pub name: String,
}

impl EdgeNodeDetailResponse {
    pub fn new(groups: Vec<crate::models::NodeGroup>, has_services: bool, hash_id: String, id: i64, modules: crate::models::EdgeNodeModules, name: String) -> EdgeNodeDetailResponse {
        EdgeNodeDetailResponse {
            groups,
            has_services,
            hash_id,
            id,
            modules: Box::new(modules),
            name,
        }
    }
}


