/*
 * Edge Node API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceBindRequest {
    #[serde(rename = "service_id")]
    pub service_id: i64,
    #[serde(rename = "variables")]
    pub variables: Vec<crate::models::Variable>,
}

impl ServiceBindRequest {
    pub fn new(service_id: i64, variables: Vec<crate::models::Variable>) -> ServiceBindRequest {
        ServiceBindRequest {
            service_id,
            variables,
        }
    }
}


