/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceBindDetailResponse {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "service_id")]
    pub service_id: i64,
    #[serde(rename = "service_name")]
    pub service_name: String,
    #[serde(rename = "variables")]
    pub variables: Vec<crate::models::Variable>,
}

impl ServiceBindDetailResponse {
    pub fn new(id: i64, service_id: i64, service_name: String, variables: Vec<crate::models::Variable>) -> ServiceBindDetailResponse {
        ServiceBindDetailResponse {
            id,
            service_id,
            service_name,
            variables,
        }
    }
}


