/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UnauthorizedEdgeNodeInfo {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl UnauthorizedEdgeNodeInfo {
    pub fn new(id: i64, reason: String) -> UnauthorizedEdgeNodeInfo {
        UnauthorizedEdgeNodeInfo {
            id,
            reason,
        }
    }
}


