/*
 * Edge Node API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UnauthorizedEdgeNodeInfo {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl UnauthorizedEdgeNodeInfo {
    pub fn new(id: i64, reason: String) -> UnauthorizedEdgeNodeInfo {
        UnauthorizedEdgeNodeInfo {
            id,
            reason,
        }
    }
}


