/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateServiceBindRequest {
    #[serde(rename = "variables")]
    pub variables: Vec<crate::models::Variable>,
}

impl UpdateServiceBindRequest {
    pub fn new(variables: Vec<crate::models::Variable>) -> UpdateServiceBindRequest {
        UpdateServiceBindRequest {
            variables,
        }
    }
}


