/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bucket {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "edge_access")]
    pub edge_access: models::EdgeAccessEnum,
}

impl Bucket {
    pub fn new(name: String, edge_access: models::EdgeAccessEnum) -> Bucket {
        Bucket {
            name,
            edge_access,
        }
    }
}

