/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketObject {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "last_modified")]
    pub last_modified: String,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "etag", skip_serializing_if = "Option::is_none")]
    pub etag: Option<String>,
}

impl BucketObject {
    pub fn new(key: String, last_modified: String, size: i32) -> BucketObject {
        BucketObject {
            key,
            last_modified,
            size,
            etag: None,
        }
    }
}

