/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EdgeAccessEnum {
    #[serde(rename = "read_only")]
    ReadOnly,
    #[serde(rename = "read_write")]
    ReadWrite,
    #[serde(rename = "restricted")]
    Restricted,

}

impl ToString for EdgeAccessEnum {
    fn to_string(&self) -> String {
        match self {
            Self::ReadOnly => String::from("read_only"),
            Self::ReadWrite => String::from("read_write"),
            Self::Restricted => String::from("restricted"),
        }
    }
}

impl Default for EdgeAccessEnum {
    fn default() -> EdgeAccessEnum {
        Self::ReadOnly
    }
}




