/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectResponseData {
    #[serde(rename = "object_key")]
    pub object_key: String,
}

impl ObjectResponseData {
    pub fn new(object_key: String) -> ObjectResponseData {
        ObjectResponseData {
            object_key,
        }
    }
}


