/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedBucket {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "edge_access", skip_serializing_if = "Option::is_none")]
    pub edge_access: Option<crate::models::EdgeAccessEnum>,
}

impl PatchedBucket {
    pub fn new() -> PatchedBucket {
        PatchedBucket {
            name: None,
            edge_access: None,
        }
    }
}


