/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseDeleteBucketData {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "edge_access")]
    pub edge_access: crate::models::EdgeAccessEnum,
}

impl ResponseDeleteBucketData {
    pub fn new(name: String, edge_access: crate::models::EdgeAccessEnum) -> ResponseDeleteBucketData {
        ResponseDeleteBucketData {
            name,
            edge_access,
        }
    }
}


