/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseDeleteBucket {
    #[serde(rename = "state")]
    pub state: crate::models::StateEnum,
    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<Box<crate::models::ResponseDeleteBucketData>>,
}

impl ResponseDeleteBucket {
    pub fn new(state: crate::models::StateEnum, data: Option<crate::models::ResponseDeleteBucketData>) -> ResponseDeleteBucket {
        ResponseDeleteBucket {
            state,
            data: if let Some(x) = data {Some(Box::new(x))} else {None},
        }
    }
}


