/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StateEnum {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "executed")]
    Executed,

}

impl ToString for StateEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Pending => String::from("pending"),
            Self::Executed => String::from("executed"),
        }
    }
}

impl Default for StateEnum {
    fn default() -> StateEnum {
        Self::Pending
    }
}




