/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuccessBucketOperation {
    #[serde(rename = "state")]
    pub state: crate::models::StateEnum,
    #[serde(rename = "data")]
    pub data: Box<crate::models::Bucket>,
}

impl SuccessBucketOperation {
    pub fn new(state: crate::models::StateEnum, data: crate::models::Bucket) -> SuccessBucketOperation {
        SuccessBucketOperation {
            state,
            data: Box::new(data),
        }
    }
}


