/*
 * Digital Certificates API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCertificateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "certificate")]
    pub certificate: String,
    #[serde(rename = "private_key")]
    pub private_key: String,
    #[serde(rename = "certificate_type", skip_serializing_if = "Option::is_none")]
    pub certificate_type: Option<CertificateType>,
    #[serde(rename = "managed", skip_serializing_if = "Option::is_none")]
    pub managed: Option<bool>,
}

impl CreateCertificateRequest {
    pub fn new(name: String, certificate: String, private_key: String) -> CreateCertificateRequest {
        CreateCertificateRequest {
            name,
            certificate,
            private_key,
            certificate_type: None,
            managed: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CertificateType {
    #[serde(rename = "edge_certificate")]
    EdgeCertificate,
    #[serde(rename = "trusted_ca_certificate")]
    TrustedCaCertificate,
}

impl Default for CertificateType {
    fn default() -> CertificateType {
        Self::EdgeCertificate
    }
}

