/*
 * Services API
 *
 * Azion Services
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResourceResponseWithTotal {
    #[serde(rename = "resources")]
    pub resources: Vec<crate::models::ResourceResponse>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl ResourceResponseWithTotal {
    pub fn new(resources: Vec<crate::models::ResourceResponse>, total: i64) -> ResourceResponseWithTotal {
        ResourceResponseWithTotal {
            resources,
            total,
        }
    }
}


