/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationInstancesGetOneResponse {
    #[serde(rename = "results")]
    pub results: Box<models::ApplicationInstancesResults>,
    #[serde(rename = "schema_version")]
    pub schema_version: i64,
}

impl ApplicationInstancesGetOneResponse {
    pub fn new(results: models::ApplicationInstancesResults, schema_version: i64) -> ApplicationInstancesGetOneResponse {
        ApplicationInstancesGetOneResponse {
            results: Box::new(results),
            schema_version,
        }
    }
}

