/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceGroupsIdResponse {
    #[serde(rename = "results")]
    pub results: Box<crate::models::DeviceGroupsResultResponse>,
    #[serde(rename = "schema_version")]
    pub schema_version: i64,
}

impl DeviceGroupsIdResponse {
    pub fn new(results: crate::models::DeviceGroupsResultResponse, schema_version: i64) -> DeviceGroupsIdResponse {
        DeviceGroupsIdResponse {
            results: Box::new(results),
            schema_version,
        }
    }
}


