/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceGroupsResponse {
    #[serde(rename = "count")]
    pub count: i64,
    #[serde(rename = "total_pages")]
    pub total_pages: i64,
    #[serde(rename = "schema_version")]
    pub schema_version: i64,
    #[serde(rename = "links")]
    pub links: Box<crate::models::DeviceGroupsResponseLinks>,
    #[serde(rename = "results")]
    pub results: Vec<crate::models::DeviceGroupsResultResponse>,
}

impl DeviceGroupsResponse {
    pub fn new(count: i64, total_pages: i64, schema_version: i64, links: crate::models::DeviceGroupsResponseLinks, results: Vec<crate::models::DeviceGroupsResultResponse>) -> DeviceGroupsResponse {
        DeviceGroupsResponse {
            count,
            total_pages,
            schema_version,
            links: Box::new(links),
            results,
        }
    }
}


