/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RulesEngineBehaviorObject {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "target")]
    pub target: Box<models::RulesEngineBehaviorObjectTarget>,
}

impl RulesEngineBehaviorObject {
    pub fn new(name: String, target: models::RulesEngineBehaviorObjectTarget) -> RulesEngineBehaviorObject {
        RulesEngineBehaviorObject {
            name,
            target: Box::new(target),
        }
    }
}

