/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRulesEngineRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i64>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "criteria")]
    pub criteria: Vec<Vec<models::RulesEngineCriteria>>,
    #[serde(rename = "behaviors")]
    pub behaviors: Vec<models::RulesEngineBehaviorEntry>,
}

impl UpdateRulesEngineRequest {
    pub fn new(name: String, criteria: Vec<Vec<models::RulesEngineCriteria>>, behaviors: Vec<models::RulesEngineBehaviorEntry>) -> UpdateRulesEngineRequest {
        UpdateRulesEngineRequest {
            name,
            order: None,
            is_active: None,
            description: None,
            criteria,
            behaviors,
        }
    }
}

